import { Router } from "express";
import authRoutes from "../modules/users/auth.routes";
import usersRoutes from "../modules/users/users.routes";
import userAdminRoutes from "../modules/users/userAdmin.routes";
import twoFactorRoutes from "../modules/users/twoFactor.routes";
import institutionRoutes from "../modules/institutions/institutions.routes";
import activityRoutes from "../modules/outsourcingActivities/activities.routes";
import contractRoutes from "../modules/contracts/contracts.routes";
import handlungsoptionRoutes from "../modules/handlungsoptionen/handlungsoptionen.routes";
import monitoringRoutes from "../modules/monitoring/monitoring.routes";
import weiterverlagerungRoutes from "../modules/weiterverlagerung/weiterverlagerung.routes";
import reportRoutes from "../modules/reports/reports.routes";
import auditLogRoutes from "../modules/auditLog/auditLog.routes";
import complianceQuellenRoutes from "../modules/compliance/quellen.routes";
import complianceAenderungenRoutes from "../modules/compliance/aenderungen.routes";
import complianceNormenRoutes from "../modules/compliance/normen.routes";
import complianceFeststellungenRoutes from "../modules/compliance/feststellungen.routes";
import complianceRatingsRoutes from "../modules/compliance/ratings.routes";
import complianceGovernanceRoutes from "../modules/compliance/governance.routes";
import complianceReportsRoutes from "../modules/compliance/reports.routes";
import complianceReferenceRoutes from "../modules/compliance/reference.routes";
import nachweiseRoutes from "../modules/nachweise/nachweise.routes";
import revisionsUniversumRoutes from "../modules/revisions/universum.routes";
import revisionsPruefungenRoutes from "../modules/revisions/pruefungen.routes";
import revisionsFeststellungenRoutes from "../modules/revisions/feststellungen.routes";
import revisionsPersonalRoutes from "../modules/revisions/personal.routes";
import revisionsGovernanceRoutes from "../modules/revisions/governance.routes";
import revisionsReportsRoutes from "../modules/revisions/reports.routes";
import externePruefungenRoutes from "../modules/revisions/externePruefungen.routes";
import accountingBalanceSheetsRoutes from "../modules/accounting/balanceSheets.routes";
import accountingIncomeStatementsRoutes from "../modules/accounting/incomeStatements.routes";
import accountingNotesRoutes from "../modules/accounting/notes.routes";
import accountingManagementReportsRoutes from "../modules/accounting/managementReports.routes";
import icsBusinessProcessesRoutes from "../modules/ics/businessProcesses.routes";
import icsControlsRoutes from "../modules/ics/controls.routes";
import icsControlTestsRoutes from "../modules/ics/controlTests.routes";
import icsPolicyDocumentsRoutes from "../modules/ics/policyDocuments.routes";
import ictProvidersRoutes from "../modules/ictRegister/providers.routes";
import ictArrangementsRoutes from "../modules/ictRegister/arrangements.routes";
import risikomanagementInventurRoutes from "../modules/risikomanagement/inventur.routes";
import risikomanagementStrategienRoutes from "../modules/risikomanagement/strategien.routes";
import risikomanagementRtfRoutes from "../modules/risikomanagement/risikotragfaehigkeit.routes";
import risikomanagementReportsRoutes from "../modules/risikomanagement/reports.routes";
import risikomanagementKapitalplanungRoutes from "../modules/risikomanagement/kapitalplanung.routes";
import risikomanagementStresstestsRoutes from "../modules/risikomanagement/stresstests.routes";
import itRisikoStrategieRoutes from "../modules/itRisiko/strategie.routes";
import itRisikoAssetsRoutes from "../modules/itRisiko/assets.routes";
import itRisikoRisikenRoutes from "../modules/itRisiko/risiken.routes";
import itRisikoVorfaelleRoutes from "../modules/itRisiko/vorfaelle.routes";
import { requireAuth } from "../middleware/auth";

export const router = Router();

router.use("/auth", authRoutes);

// Everything below requires a valid JWT — requireAuth populates req.user, which every
// requirePermission() check and every withAudit() call downstream depends on.
router.use(requireAuth);
router.use("/institutions", institutionRoutes);
router.use("/activities", activityRoutes);
router.use("/activities/:activityId/contract", contractRoutes);
router.use("/activities/:activityId/handlungsoption", handlungsoptionRoutes);
router.use("/activities/:activityId/monitoring", monitoringRoutes);
router.use("/activities/:activityId/weiterverlagerung", weiterverlagerungRoutes);
router.use("/reports", reportRoutes);
router.use("/audit-log", auditLogRoutes);
router.use("/users", usersRoutes);
router.use("/users/admin", userAdminRoutes);
router.use("/users/me/2fa", twoFactorRoutes);
router.use("/compliance/quellen", complianceQuellenRoutes);
router.use("/compliance/aenderungen", complianceAenderungenRoutes);
router.use("/compliance/normen", complianceNormenRoutes);
router.use("/compliance/feststellungen", complianceFeststellungenRoutes);
router.use("/compliance/ratings", complianceRatingsRoutes);
router.use("/compliance/governance", complianceGovernanceRoutes);
router.use("/compliance/reports", complianceReportsRoutes);
router.use("/compliance/reference", complianceReferenceRoutes);
router.use("/nachweise", nachweiseRoutes);
router.use("/revisions/universum", revisionsUniversumRoutes);
router.use("/revisions/pruefungen", revisionsPruefungenRoutes);
router.use("/revisions/feststellungen", revisionsFeststellungenRoutes);
router.use("/revisions/personal", revisionsPersonalRoutes);
router.use("/revisions/governance", revisionsGovernanceRoutes);
router.use("/revisions/reports", revisionsReportsRoutes);
router.use("/revisions/externe-pruefungen", externePruefungenRoutes);
router.use("/accounting/balance-sheets", accountingBalanceSheetsRoutes);
router.use("/accounting/income-statements", accountingIncomeStatementsRoutes);
router.use("/accounting/notes", accountingNotesRoutes);
router.use("/accounting/management-reports", accountingManagementReportsRoutes);
router.use("/ics/processes", icsBusinessProcessesRoutes);
router.use("/ics/controls", icsControlsRoutes);
router.use("/ics/control-tests", icsControlTestsRoutes);
router.use("/ics/policies", icsPolicyDocumentsRoutes);
router.use("/ict-register/providers", ictProvidersRoutes);
router.use("/ict-register/arrangements", ictArrangementsRoutes);
router.use("/risikomanagement/inventur", risikomanagementInventurRoutes);
router.use("/risikomanagement/strategien", risikomanagementStrategienRoutes);
router.use("/risikomanagement/risikotragfaehigkeit", risikomanagementRtfRoutes);
router.use("/risikomanagement/reports", risikomanagementReportsRoutes);
router.use("/risikomanagement/kapitalplanung", risikomanagementKapitalplanungRoutes);
router.use("/risikomanagement/stresstests", risikomanagementStresstestsRoutes);
router.use("/it-risiko/strategie", itRisikoStrategieRoutes);
router.use("/it-risiko/assets", itRisikoAssetsRoutes);
router.use("/it-risiko/risiken", itRisikoRisikenRoutes);
router.use("/it-risiko/vorfaelle", itRisikoVorfaelleRoutes);
