import { Router } from "express";
import authRoutes from "../modules/users/auth.routes";
import usersRoutes from "../modules/users/users.routes";
import institutionRoutes from "../modules/institutions/institutions.routes";
import activityRoutes from "../modules/outsourcingActivities/activities.routes";
import contractRoutes from "../modules/contracts/contracts.routes";
import handlungsoptionRoutes from "../modules/handlungsoptionen/handlungsoptionen.routes";
import monitoringRoutes from "../modules/monitoring/monitoring.routes";
import weiterverlagerungRoutes from "../modules/weiterverlagerung/weiterverlagerung.routes";
import reportRoutes from "../modules/reports/reports.routes";
import auditLogRoutes from "../modules/auditLog/auditLog.routes";
import complianceQuellenRoutes from "../modules/compliance/quellen.routes";
import complianceAenderungenRoutes from "../modules/compliance/aenderungen.routes";
import complianceNormenRoutes from "../modules/compliance/normen.routes";
import complianceFeststellungenRoutes from "../modules/compliance/feststellungen.routes";
import complianceRatingsRoutes from "../modules/compliance/ratings.routes";
import complianceGovernanceRoutes from "../modules/compliance/governance.routes";
import complianceReportsRoutes from "../modules/compliance/reports.routes";
import complianceReferenceRoutes from "../modules/compliance/reference.routes";
import nachweiseRoutes from "../modules/nachweise/nachweise.routes";
import revisionsUniversumRoutes from "../modules/revisions/universum.routes";
import revisionsPruefungenRoutes from "../modules/revisions/pruefungen.routes";
import revisionsFeststellungenRoutes from "../modules/revisions/feststellungen.routes";
import revisionsPersonalRoutes from "../modules/revisions/personal.routes";
import revisionsGovernanceRoutes from "../modules/revisions/governance.routes";
import revisionsReportsRoutes from "../modules/revisions/reports.routes";
import doraRoutes from "../modules/dora/dora.routes";
import doraSubOutsourcingRoutes from "../modules/dora/doraSubOutsourcing.routes";
import { requireAuth } from "../middleware/auth";

export const router = Router();

router.use("/auth", authRoutes);

// Everything below requires a valid JWT — requireAuth populates req.user, which every
// requirePermission() check and every withAudit() call downstream depends on.
router.use(requireAuth);
router.use("/institutions", institutionRoutes);
router.use("/activities", activityRoutes);
router.use("/activities/:activityId/contract", contractRoutes);
router.use("/activities/:activityId/handlungsoption", handlungsoptionRoutes);
router.use("/activities/:activityId/monitoring", monitoringRoutes);
router.use("/activities/:activityId/weiterverlagerung", weiterverlagerungRoutes);
router.use("/reports", reportRoutes);
router.use("/audit-log", auditLogRoutes);
router.use("/users", usersRoutes);
router.use("/compliance/quellen", complianceQuellenRoutes);
router.use("/compliance/aenderungen", complianceAenderungenRoutes);
router.use("/compliance/normen", complianceNormenRoutes);
router.use("/compliance/feststellungen", complianceFeststellungenRoutes);
router.use("/compliance/ratings", complianceRatingsRoutes);
router.use("/compliance/governance", complianceGovernanceRoutes);
router.use("/compliance/reports", complianceReportsRoutes);
router.use("/compliance/reference", complianceReferenceRoutes);
router.use("/nachweise", nachweiseRoutes);
router.use("/revisions/universum", revisionsUniversumRoutes);
router.use("/revisions/pruefungen", revisionsPruefungenRoutes);
router.use("/revisions/feststellungen", revisionsFeststellungenRoutes);
router.use("/revisions/personal", revisionsPersonalRoutes);
router.use("/revisions/governance", revisionsGovernanceRoutes);
router.use("/revisions/reports", revisionsReportsRoutes);
router.use("/dora/arrangements", doraRoutes);
router.use("/dora/arrangements/:arrangementId/sub-outsourcing", doraSubOutsourcingRoutes);
