-- AlterEnum
ALTER TYPE "AccessModule" ADD VALUE 'ACCOUNTING';
ALTER TYPE "AccessModule" ADD VALUE 'IKS';
ALTER TYPE "AccessModule" ADD VALUE 'RISIKOMANAGEMENT';
ALTER TYPE "AccessModule" ADD VALUE 'IT_RISIKO';
